
package employee.implement;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EmployeeimpService", targetNamespace = "http://implement.employee/", wsdlLocation = "http://localhost:9999/ws/hello?wsdl")
public class EmployeeimpService
    extends Service
{

    private final static URL EMPLOYEEIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException EMPLOYEEIMPSERVICE_EXCEPTION;
    private final static QName EMPLOYEEIMPSERVICE_QNAME = new QName("http://implement.employee/", "EmployeeimpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/ws/hello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPLOYEEIMPSERVICE_WSDL_LOCATION = url;
        EMPLOYEEIMPSERVICE_EXCEPTION = e;
    }

    public EmployeeimpService() {
        super(__getWsdlLocation(), EMPLOYEEIMPSERVICE_QNAME);
    }

    public EmployeeimpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPLOYEEIMPSERVICE_QNAME, features);
    }

    public EmployeeimpService(URL wsdlLocation) {
        super(wsdlLocation, EMPLOYEEIMPSERVICE_QNAME);
    }

    public EmployeeimpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPLOYEEIMPSERVICE_QNAME, features);
    }

    public EmployeeimpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeeimpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Employeeimp
     */
    @WebEndpoint(name = "EmployeeimpPort")
    public Employeeimp getEmployeeimpPort() {
        return super.getPort(new QName("http://implement.employee/", "EmployeeimpPort"), Employeeimp.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Employeeimp
     */
    @WebEndpoint(name = "EmployeeimpPort")
    public Employeeimp getEmployeeimpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://implement.employee/", "EmployeeimpPort"), Employeeimp.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPLOYEEIMPSERVICE_EXCEPTION!= null) {
            throw EMPLOYEEIMPSERVICE_EXCEPTION;
        }
        return EMPLOYEEIMPSERVICE_WSDL_LOCATION;
    }

}
